In [3]:
import numpy as np

In [5]:
myarr=np.array([[1,2,3,4,]], np.int64)

In [3]:
myarr[0,1]

2

array([1, 2, 3, 4, 5], dtype=int64) this is 1d array

In [5]:
myarr.shape

(1, 4)

(1,4) show isme 1 row aur 4 column hai

In [7]:
myarr.dtype

dtype('int64')

In [15]:
myarr[0,1]=45

In [17]:
myarr

array([[ 1, 45,  3,  4]], dtype=int64)

There are 5 general mechanism for creating arrays:
1. Conversion from other python stuctures(e.g., list ,tuple)

In [24]:
listarry=np.array([[1,2,3,4],[5,6,7,8],[4,3,2,1]])

In [26]:
listarry

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 2, 1]])

In [28]:
listarry.dtype

dtype('int32')

In [30]:
listarry.shape

(3, 4)

In [32]:
listarry.size

12

***Intrinsic numpy array creation objects (eg arange,ones,zeros,etc)***

In [35]:
zeros = np.zeros((2,3))

In [39]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
range = np.arange(15)

In [45]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
lspace = np.linspace(1,5,12)

In [49]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

**linspace ye line mujhe np.linspace(1,5,12) 1 se 5 tak equaliy linearly spaced 12 element dega**

In [54]:
emp = np.empty((6,5))

In [56]:
emp

array([[7.65412012e-312, 1.01283457e-321, 0.00000000e+000,
        0.00000000e+000, 2.45942240e+198],
       [1.16097020e-028, 8.26440822e-072, 2.92732919e-028,
        3.88661104e-033, 1.04917183e-153],
       [5.23081515e-143, 1.10817982e-047, 9.68601697e-071,
        7.77731345e-071, 1.52851185e+160],
       [5.69231480e-143, 3.59751658e+252, 1.46901661e+179,
        8.37404147e+242, 4.31999013e-096],
       [4.82337723e+228, 6.64079265e-066, 6.22692629e+174,
        4.26784315e-090, 5.34847320e-038],
       [1.58804164e-076, 5.04621343e+180, 1.94918963e-153,
        1.14484251e+243, 2.59903827e-144]])

In [58]:
emp_like = np.empty_like(lspace)

In [60]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [74]:
ide = np.identity(45)

In [76]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [78]:
ide.dtype

dtype('float64')

In [80]:
ide.shape

(45, 45)

In [82]:
arr = np.arange(99)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [94]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [100]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

***1d array me convert kar diya isne arr.ravel()***

In [103]:
arr.shape

(99,)

                                                ***Numpy axis***

*** axis 0 row ki taraf axis 1 column ki taraf ***

In [15]:
x = [[1,2,3],[1,2,3],[1,2,3]]

In [17]:
ar = np.array(x)

In [19]:
ar

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [130]:
ar.sum(axis=0)

array([3, 6, 9])

In [132]:
ar.sum(axis=1)

array([6, 6, 6])

In [134]:
ar.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

***ar.T T is use to taranspos the array***

In [137]:
ar.flat

In [139]:
for item in ar.flat:
    print(item)

1
2
3
1
2
3
1
2
3


In [143]:
ar.ndim

2

In [145]:
ar.size

9

In [147]:
ar.nbytes

36

In [7]:
one = np.array([13,45,3,2])

In [9]:
one.argmax()

1

In [153]:
one.argmin()

3

In [155]:
one.argsort()

array([3, 2, 0, 1], dtype=int64)

In [11]:
one.argsort()

array([3, 2, 0, 1], dtype=int64)

In [21]:
ar

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [33]:
ar.argmax()

2

In [37]:
ar.argmax(axis=0)

array([0, 0, 0], dtype=int64)

In [39]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [45]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [47]:
ar

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
ar2=np.array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [51]:
ar+ar2

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [53]:
ar*ar2

array([[1, 4, 9],
       [1, 4, 9],
       [1, 4, 9]])

In [55]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [57]:
ar.sum()

18

In [59]:
ar.max()

3

In [61]:
ar.min()

1

In [63]:
ar

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [67]:
type(np.where(ar>5))

tuple

In [71]:
np.where(ar>5)

(array([], dtype=int64), array([], dtype=int64))

In [73]:
np.count_nonzero(ar)

9

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [77]:
import sys

In [79]:
py_ar=[0,4,55,2]

In [87]:
np_ar = np.array(py_ar)

In [83]:
sys.getsizeof(1)*len(py_ar)

112

In [89]:
np_ar.itemsize*np_ar.size

16